### ISSUE TITLE
Datenexport per Excel?

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/trintel#100]
Wäre es möglich die Daten per Excel zu exportieren, damit man sie für eine Bewertung auswerten kann? Manchmal ist die Zeit zwischen zwei Planspielen zu knapp. es wäre gut die Daten so zu sichern...

**Comment by b3z** [comment]
added in #110 coming in the next release no the admin statistics overview page.

**Comment by b3z** [comment]
![image](https://github.com/user-attachments/assets/1d09b1ac-b189-4d7b-8b72-7ec644942ac4)
