### ISSUE TITLE
New businessgame with trintel in week 46 (trial in week 45)

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/trintel#105]
Hallo liebes Trintel - Team,

Können wir Trintel in Woche 45  (ab dem 04.11.24) testen und Woche 46 mit ca 40 Accounts auf unserem Server ausführen? 

Bitte nehmen ggf. Kontakt zu Benjamin Lücke auf, damit alles möglichst funktioniert. 

Könntet Ihr in KW 46 kurzfristig auf Nachfragen reagieren Wir werden bestimmt das eine oder andere Problem haben...

Lieben Gruß
Matthias

**Comment by Felioh** [comment]
Hi @KrasRBZWirtschaftKiel,

Wir haben momentan zwar nicht unglaublich viel Zeit, aber 4.11. sollten wir schaffen (zumindest die wichtigen issues).

VG Felix

**Comment by KrasRBZWirtschaftKiel** [comment]
Hi Felix,

Super! Vielen Dank.
Alles weitere zur Abrechnung etc. gern direkt per Mail an mich und Benjamin.

Lieben Gruß
Matthias

RBZ Wirtschaft . Kiel
Westring 444
24118 Kiel
t +49 431 1698 524
f +49 431 1698 444
e ***@***.******@***.***>



Von: Felix Ohnesorge ***@***.***>
Gesendet: Montag, 14. Oktober 2024 13:07
An: trintel/trintel ***@***.***>
Cc: Matthias Kraski ***@***.***>; Mention ***@***.***>
Betreff: Re: [trintel/trintel] New businessgame with trintel in week 46 (trial in week 45) (Issue #105)


Hi @KrasRBZWirtschaftKiel<https://github.com/KrasRBZWirtschaftKiel>,

Wir haben momentan zwar nicht unglaublich viel Zeit, aber 4.11. sollten wir schaffen (zumindest die wichtigen issues).

VG Felix
