### ISSUE TITLE
Transaktionen:

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/trintel#97]
Alle Transaktionen sollten von Lehrern angelegt werden können, und auch beim Beginn der Transaktion den Schülern als Auswahl zur Verfügung stehen. Die im Admin - Panel sichtbaren Transaktionen sind derzeit nicht alle verfügbar.

**Comment by Felioh** [comment]
@KrasRBZWirtschaftKiel, dann wird wahrscheinlich das ganze Konzept von Standard/Default Aktionen nicht mehr gebraucht, korrekt?

**Comment by KrasRBZWirtschaftKiel** [comment]
Ja, fast alle Aktionen sollten am Anfang verfügbar sein (bis auf die Rechnungsstellung, die Bezahlung und Lieferung). Ohne Rechnung sollte es nicht möglich sein zu zahlen und zu liefern. Vor der Rechnung (Invoice) muss eine Bestellung (Order) erfolgen.

Wichtig wäre, dass alle sonstigen Aktionen, also auch die von den Lehrern zusätzlich hinzugefügten, auch am Anfang der Transaktionskette ausgewählt werden können.  Wir benötigen z.B. einen „Call for Tender“ (eine Ausschreibung) als zusätzliche Aktion.

Kann man es hinbekommen, dass Lehrer auch immer die englische Bezeichnung mit angeben müssen, so dass die Aktion dann korrekt im Ausland benannt wird?

Von: Felix Ohnesorge ***@***.***>
Antworten an: trintel/trintel ***@***.***>
Datum: Sonntag, 7. Juli 2024 um 17:10
An: trintel/trintel ***@***.***>
Cc: Matthias Kraski ***@***.***>, Mention ***@***.***>
Betreff: Re: [trintel/trintel] Transaktionen: (Issue #97)


@KrasRBZWirtschaftKiel<https://github.com/KrasRBZWirtschaftKiel>, dann wird wahrscheinlich das ganze Konzept von Standard/Default Aktionen nicht mehr gebraucht, korrekt?
